---
title: "Workflow ProbODER Real data"
author: "Claire Descombes"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: styles.css
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=8, fig.height=6)
```

## Import packages

#### Import

```{r, echo=FALSE, include=FALSE}
# Set source directory
source_directory <- '~/Documents/GitHub/proboder/Functions/'

# Source necessary functions
source(file.path(source_directory, 'initialization.R'))
source(file.path(source_directory, 'inference.R'))
source(file.path(source_directory, 'processing_saving_loading.R'))
source(file.path(source_directory, 'scoring.R'))
source(file.path(source_directory, 'plotting.R'))

# Load or install necessary packages
load_required_packages()
```


#-------------------------------------------------------------------------------

## Test Example

30 days.

#### Import data

```{r, fig.width=8, fig.height=6}
# ------
# Import
# ------

# Choose data to be imported
region <- 'GE' # 'BE' or 'GE' available 
daily_or_weekly <- 'daily' # choose either 'daily' or 'weekly'
directory_data <- 
  "~/Documents/GitHub/proboder/Data/real" # directory of data

# Import data
data <- load_data(region = region,
                  daily_or_weekly = daily_or_weekly,
                  directory_data = directory_data)
obs_with_noise <- data$obs
pop <- data$population

# Take only first 30 days
tmax <- 30
obs_to_use <- obs_with_noise[1:tmax,]

# Visualisation
(real_compartments <- plotting_real_data(obs = obs_to_use))
```

#### Perform inference

```{r, fig.width=8, fig.height=6}
# ---------
# Inference
# ---------

model <- 'SEIR' # model to be simulated 

steps <- 1 # steps for time grid
max_time <- tmax # max time for time grid

lambda <- 1/(2.6) # latency rate, ref value 1/(2.6)
gamma <- 1/(2.6) # recovery rate, ref value 1/(2.6)
if (model == 'SEIRD') {
  eta <- 0.024*(1/15) # fatality rate, ref value 0.024*(1/15)
} else if (model == 'SEIR') {
  eta <- 0
}

noise_obs <- 50 # noise of observations
l <- 5 # lengthscale
noise_wiener_X <- 1 # noise of the Wiener process associated with X
noise_wiener_U <- 0.1 # noise of the Wiener process associated with U
beta0 = 0.8 # starting transmission rate
beta0prime <- 0 # starting 1st derivative of transmission rate
jit <- 1e-1 # value for jitter on innovation covariance

# Initialize
initial_params <-
    initialization(model = model, obs = obs_to_use,
                   beta0 = beta0, beta0prime = beta0prime,
                   lambda = lambda, gamma = gamma, eta = eta,
                   l = l, scale = 1, noise_obs = noise_obs,
                   noise_X = sqrt(noise_obs), noise_U = 0.2,
                   noise_wiener_X = noise_wiener_X, 
                   noise_wiener_U = noise_wiener_U,
                   pop = pop,
                   start_S = NULL, start_E = NULL, 
                   start_I = NULL, start_R = NULL,
                   start_D = NULL)

# Generate time grids for inference
grids <- generate_grid(obs_to_use, num_points_between = 0, daily_or_weekly)

# Run inference
inference_results <- inference(model = model, 
                               grids = grids, 
                               obs = obs_to_use, 
                               jit = jit, 
                               initial_params = initial_params)

# Process data for scoring and visualization
processed_data <- process_data(inference_results = inference_results,
                               grids = grids,
                               model = model,
                               pop = pop, 
                               lambda = lambda, 
                               gamma = gamma, 
                               eta = eta)
U_plot <- processed_data$U_plot
X_plot <- processed_data$X_plot
R_plot <- processed_data$R_plot
cond_plot <- processed_data$cond_plot

# Plot compartment counts inferred from real data
(compartments <- 
    plot_compartments_real(
      obs = obs_to_use, 
      X_plot = X_plot))

# Plot all but S compartment counts inferred from real data
(compartments_except_S <- 
  plot_compartments_except_S_real(
    obs = obs_to_use, 
    X_plot = X_plot))

# Plot compartment counts separately
plots_sep <- 
  plot_compartments_separately_real(
    obs = obs_to_use,
    X_plot = X_plot)

num_plots <- length(plots_sep)
invisible(grid_plots_sep <- grid.arrange(
    grobs = plots_sep,
    ncol = 2,
    nrow = ceiling(num_plots/2)))

# Plot transmission rate with 95% confidence interval
(transmission_rate_with_CI <- 
    plot_transmission_rate_with_CI(
      U_plot = U_plot, 
      latency_rate = lambda, 
      recovery_rate = gamma, 
      fatality_rate = eta, 
      lengthscale = l))

# Plot reproduction number with approx. 95% confidence interval
(reproduction_number_with_CI <- 
    plot_reproduction_number_with_CI(
      R_plot = R_plot, 
      latency_rate = lambda, 
      recovery_rate = gamma, 
      fatality_rate = eta, 
      lengthscale = l))

# Plot condition numbers of the innovation covariances 
# and covariance matrices
cond_plots <- 
    plot_condition_numbers(cond_plot)

number_plots <- length(cond_plots)
invisible(condition_numbers <- grid.arrange(
    grobs = cond_plots,
    ncol = 2,
    nrow = ceiling(number_plots/2)))
```


#-------------------------------------------------------------------------------

## Test A

100 days.

#### Import data

```{r, fig.width=8, fig.height=6}
# ------
# Import
# ------

# Choose data to be imported
region <- 'GE' # 'BE' or 'GE' available 
daily_or_weekly <- 'daily' # choose either 'daily' or 'weekly'
directory_data <- 
  "~/Documents/GitHub/proboder/Data/real" # directory of data

# Import data
data <- load_data(region = region,
                  daily_or_weekly = daily_or_weekly,
                  directory_data = directory_data)
obs_with_noise <- data$obs
pop <- data$population

# Take only first 100 days
tmax <- 100
obs_to_use <- obs_with_noise[1:tmax,]

# Visualisation
(real_compartments <- plotting_real_data(obs = obs_to_use))
```

#### Perform inference

```{r, fig.width=8, fig.height=6}
# ---------
# Inference
# ---------

model <- 'SEIR' # model to be simulated 

steps <- 1 # steps for time grid
max_time <- tmax # max time for time grid

lambda <- 1/(2.6) # latency rate, ref value 1/(2.6)
gamma <- 1/(2.6) # recovery rate, ref value 1/(2.6)
if (model == 'SEIRD') {
  eta <- 0.024*(1/15) # fatality rate, ref value 0.024*(1/15)
} else if (model == 'SEIR') {
  eta <- 0
}

noise_obs <- 50 # noise of observations
l <- 5 # lengthscale
noise_wiener_X <- 1 # noise of the Wiener process associated with X
noise_wiener_U <- 0.01 # noise of the Wiener process associated with U
beta0 = 0.8 # starting transmission rate
beta0prime <- 0 # starting 1st derivative of transmission rate
jit <- 1e-1 # value for jitter on innovation covariance

# Initialize
initial_params <-
    initialization(model = model, obs = obs_to_use,
                   beta0 = beta0, beta0prime = beta0prime,
                   lambda = lambda, gamma = gamma, eta = eta,
                   l = l, scale = 1, noise_obs = noise_obs,
                   noise_X = sqrt(noise_obs), noise_U = 0.2,
                   noise_wiener_X = noise_wiener_X, 
                   noise_wiener_U = noise_wiener_U,
                   pop = pop,
                   start_S = NULL, start_E = NULL, 
                   start_I = NULL, start_R = NULL,
                   start_D = NULL)

# Generate time grids for inference
grids <- generate_grid(obs_to_use, num_points_between = 0, daily_or_weekly)

# Run inference
inference_results <- inference(model = model, 
                               grids = grids, 
                               obs = obs_to_use, 
                               jit = jit, 
                               initial_params = initial_params)

# Process data for scoring and visualization
processed_data <- process_data(inference_results = inference_results,
                               grids = grids,
                               model = model,
                               pop = pop, 
                               lambda = lambda, 
                               gamma = gamma, 
                               eta = eta)
U_plot <- processed_data$U_plot
X_plot <- processed_data$X_plot
R_plot <- processed_data$R_plot
cond_plot <- processed_data$cond_plot

# Plot compartment counts inferred from real data
(compartments <- 
    plot_compartments_real(
      obs = obs_to_use, 
      X_plot = X_plot))

# Plot all but S compartment counts inferred from real data
(compartments_except_S <- 
  plot_compartments_except_S_real(
    obs = obs_to_use, 
    X_plot = X_plot))

# Plot compartment counts separately
plots_sep <- 
  plot_compartments_separately_real(
    obs = obs_to_use,
    X_plot = X_plot)

num_plots <- length(plots_sep)
invisible(grid_plots_sep <- grid.arrange(
    grobs = plots_sep,
    ncol = 2,
    nrow = ceiling(num_plots/2)))

# Plot transmission rate with 95% confidence interval
(transmission_rate_with_CI <- 
    plot_transmission_rate_with_CI(
      U_plot = U_plot, 
      latency_rate = lambda, 
      recovery_rate = gamma, 
      fatality_rate = eta, 
      lengthscale = l))

# Plot reproduction number with approx. 95% confidence interval
(reproduction_number_with_CI <- 
    plot_reproduction_number_with_CI(
      R_plot = R_plot, 
      latency_rate = lambda, 
      recovery_rate = gamma, 
      fatality_rate = eta, 
      lengthscale = l))

# Plot condition numbers of the innovation covariances 
# and covariance matrices
cond_plots <- 
    plot_condition_numbers(cond_plot)

number_plots <- length(cond_plots)
invisible(condition_numbers <- grid.arrange(
    grobs = cond_plots,
    ncol = 2,
    nrow = ceiling(number_plots/2)))
```







#-------------------------------------------------------------------------------

## Test B

Data from BE, 100 days.

#### Import data

```{r, fig.width=8, fig.height=6}
# ------
# Import
# ------

# Choose data to be imported
region <- 'BE' # 'BE' or 'GE' available 
daily_or_weekly <- 'daily' # choose either 'daily' or 'weekly'
directory_data <- 
  "~/Documents/GitHub/proboder/Data/real" # directory of data

# Import data
data <- load_data(region = region,
                  daily_or_weekly = daily_or_weekly,
                  directory_data = directory_data)
obs_with_noise <- data$obs
pop <- data$population

# Take only first 100 days
tmax <- 100
obs_to_use <- obs_with_noise[1:tmax,]

# Visualisation
(real_compartments <- plotting_real_data(obs = obs_to_use))
```

#### Perform inference

```{r, fig.width=8, fig.height=6}
# ---------
# Inference
# ---------

model <- 'SEIR' # model to be simulated 

steps <- 1 # steps for time grid
max_time <- tmax # max time for time grid

lambda <- 1/(2.6) # latency rate, ref value 1/(2.6)
gamma <- 1/(2.6) # recovery rate, ref value 1/(2.6)
if (model == 'SEIRD') {
  eta <- 0.024*(1/15) # fatality rate, ref value 0.024*(1/15)
} else if (model == 'SEIR') {
  eta <- 0
}

noise_obs <- 50 # noise of observations
l <- 5 # lengthscale
noise_wiener_X <- 1 # noise of the Wiener process associated with X
noise_wiener_U <- 0.1 # noise of the Wiener process associated with U
beta0 = 0.8 # starting transmission rate
beta0prime <- 0 # starting 1st derivative of transmission rate
jit <- 1e-1 # value for jitter on innovation covariance

# Initialize
initial_params <-
    initialization(model = model, obs = obs_to_use,
                   beta0 = beta0, beta0prime = beta0prime,
                   lambda = lambda, gamma = gamma, eta = eta,
                   l = l, scale = 1, noise_obs = noise_obs,
                   noise_X = sqrt(noise_obs), noise_U = 0.2,
                   noise_wiener_X = noise_wiener_X, 
                   noise_wiener_U = noise_wiener_U,
                   pop = pop,
                   start_S = NULL, start_E = NULL, 
                   start_I = NULL, start_R = NULL,
                   start_D = NULL)

# Generate time grids for inference
grids <- generate_grid(obs_to_use, num_points_between = 0, daily_or_weekly)

# Run inference
inference_results <- inference(model = model, 
                               grids = grids, 
                               obs = obs_to_use, 
                               jit = jit, 
                               initial_params = initial_params)

# Process data for scoring and visualization
processed_data <- process_data(inference_results = inference_results,
                               grids = grids,
                               model = model,
                               pop = pop, 
                               lambda = lambda, 
                               gamma = gamma, 
                               eta = eta)
U_plot <- processed_data$U_plot
X_plot <- processed_data$X_plot
R_plot <- processed_data$R_plot
cond_plot <- processed_data$cond_plot

# Plot compartment counts inferred from real data
(compartments <- 
    plot_compartments_real(
      obs = obs_to_use, 
      X_plot = X_plot))

# Plot all but S compartment counts inferred from real data
(compartments_except_S <- 
  plot_compartments_except_S_real(
    obs = obs_to_use, 
    X_plot = X_plot))

# Plot compartment counts separately
plots_sep <- 
  plot_compartments_separately_real(
    obs = obs_to_use,
    X_plot = X_plot)

num_plots <- length(plots_sep)
invisible(grid_plots_sep <- grid.arrange(
    grobs = plots_sep,
    ncol = 2,
    nrow = ceiling(num_plots/2)))

# Plot transmission rate with 95% confidence interval
(transmission_rate_with_CI <- 
    plot_transmission_rate_with_CI(
      U_plot = U_plot, 
      latency_rate = lambda, 
      recovery_rate = gamma, 
      fatality_rate = eta, 
      lengthscale = l))

# Plot reproduction number with approx. 95% confidence interval
(reproduction_number_with_CI <- 
    plot_reproduction_number_with_CI(
      R_plot = R_plot, 
      latency_rate = lambda, 
      recovery_rate = gamma, 
      fatality_rate = eta, 
      lengthscale = l))

# Plot condition numbers of the innovation covariances 
# and covariance matrices
cond_plots <- 
    plot_condition_numbers(cond_plot)

number_plots <- length(cond_plots)
invisible(condition_numbers <- grid.arrange(
    grobs = cond_plots,
    ncol = 2,
    nrow = ceiling(number_plots/2)))
```



#-------------------------------------------------------------------------------

## Test C

Data from BE, 300 days.

#### Import data

```{r, fig.width=8, fig.height=6}
# ------
# Import
# ------

# Choose data to be imported
region <- 'BE' # 'BE' or 'GE' available 
daily_or_weekly <- 'daily' # choose either 'daily' or 'weekly'
directory_data <- 
  "~/Documents/GitHub/proboder/Data/real" # directory of data

# Import data
data <- load_data(region = region,
                  daily_or_weekly = daily_or_weekly,
                  directory_data = directory_data)
obs_with_noise <- data$obs
pop <- data$population

# Take only first 300 days
tmax <- 300
obs_to_use <- obs_with_noise[1:tmax,]

# Visualisation
(real_compartments <- plotting_real_data(obs = obs_to_use))
```

#### Perform inference

```{r, fig.width=8, fig.height=6}
# ---------
# Inference
# ---------

model <- 'SEIR' # model to be simulated 

steps <- 1 # steps for time grid
max_time <- tmax # max time for time grid

lambda <- 1/(2.6) # latency rate, ref value 1/(2.6)
gamma <- 1/(2.6) # recovery rate, ref value 1/(2.6)
if (model == 'SEIRD') {
  eta <- 0.024*(1/15) # fatality rate, ref value 0.024*(1/15)
} else if (model == 'SEIR') {
  eta <- 0
}

noise_obs <- 50 # noise of observations
l <- 5 # lengthscale
noise_wiener_X <- 0.01 # noise of the Wiener process associated with X
noise_wiener_U <- 0.01 # noise of the Wiener process associated with U
beta0 = 0.8 # starting transmission rate
beta0prime <- 0 # starting 1st derivative of transmission rate
jit <- 1e-1 # value for jitter on innovation covariance

# Initialize
initial_params <-
    initialization(model = model, obs = obs_to_use,
                   beta0 = beta0, beta0prime = beta0prime,
                   lambda = lambda, gamma = gamma, eta = eta,
                   l = l, scale = 1, noise_obs = noise_obs,
                   noise_X = sqrt(noise_obs), noise_U = 0.2,
                   noise_wiener_X = noise_wiener_X, 
                   noise_wiener_U = noise_wiener_U,
                   pop = pop,
                   start_S = NULL, start_E = NULL, 
                   start_I = NULL, start_R = NULL,
                   start_D = NULL)

# Generate time grids for inference
grids <- generate_grid(obs_to_use, num_points_between = 0, daily_or_weekly)

# Run inference
inference_results <- inference(model = model, 
                               grids = grids, 
                               obs = obs_to_use, 
                               jit = jit, 
                               initial_params = initial_params)

# Process data for scoring and visualization
processed_data <- process_data(inference_results = inference_results,
                               grids = grids,
                               model = model,
                               pop = pop, 
                               lambda = lambda, 
                               gamma = gamma, 
                               eta = eta)
U_plot <- processed_data$U_plot
X_plot <- processed_data$X_plot
R_plot <- processed_data$R_plot
cond_plot <- processed_data$cond_plot

# Plot compartment counts inferred from real data
(compartments <- 
    plot_compartments_real(
      obs = obs_to_use, 
      X_plot = X_plot))

# Plot all but S compartment counts inferred from real data
(compartments_except_S <- 
  plot_compartments_except_S_real(
    obs = obs_to_use, 
    X_plot = X_plot))

# Plot compartment counts separately
plots_sep <- 
  plot_compartments_separately_real(
    obs = obs_to_use,
    X_plot = X_plot)

num_plots <- length(plots_sep)
invisible(grid_plots_sep <- grid.arrange(
    grobs = plots_sep,
    ncol = 2,
    nrow = ceiling(num_plots/2)))

# Plot transmission rate with 95% confidence interval
(transmission_rate_with_CI <- 
    plot_transmission_rate_with_CI(
      U_plot = U_plot, 
      latency_rate = lambda, 
      recovery_rate = gamma, 
      fatality_rate = eta, 
      lengthscale = l))

# Plot reproduction number with approx. 95% confidence interval
(reproduction_number_with_CI <- 
    plot_reproduction_number_with_CI(
      R_plot = R_plot, 
      latency_rate = lambda, 
      recovery_rate = gamma, 
      fatality_rate = eta, 
      lengthscale = l))

# Plot condition numbers of the innovation covariances 
# and covariance matrices
cond_plots <- 
    plot_condition_numbers(cond_plot)

number_plots <- length(cond_plots)
invisible(condition_numbers <- grid.arrange(
    grobs = cond_plots,
    ncol = 2,
    nrow = ceiling(number_plots/2)))
```


#-------------------------------------------------------------------------------

## Store data

```{r}
# -------------
# Store results
# -------------

# Every argument except directory is optional. 

directory_save <- '~/Documents/GitHub/proboder/Results/'
folder_name <- 'testB'

if (TRUE) { # Set TRUE to save
  save_processed_data(
    directory = directory_save,
    folder_name = folder_name,
    model = model,
    # Data
    inference_results = inference_results, 
    processed_data = processed_data, 
    # Plots
    real_compartments = real_compartments, 
    compartments = compartments,
    compartments_except_S = compartments_except_S,
    transmission_rate_with_CI = transmission_rate_with_CI,
    reproduction_number_with_CI = reproduction_number_with_CI,
    condition_numbers = condition_numbers,
    grid_plots_sep = grid_plots_sep)
}

# To store a table as a png file, use the manual export option from the viewer.
```